stages:
- build

# Build debug version after each commit or merge requests    
build:
  image: tychosoft/gitlabcpp:build
  stage: build
  script:
    - cmake -DCMAKE_BUILD_TYPE=Debug  --build . | tee cmake.log
    - make | tee make.log
    - ctest | tee test.log
  tags:
    - docker
  except:
    - master
  artifacts:
    expire_in: 2 weeks
    when: always
    paths:
      - ./*.log

